version: 2

sources:
  - name: gold
    # schema: gold
    # database: youTube_trending_video

    tables:
      - name: videoCategory
        meta:
          dagster:
            asset_key: ["gold", "videoCategory"]
      - name: linkVideos
        meta:
          dagster:
            asset_key: ["gold", "linkVideos"]
      - name: metricVideos
        meta:
          dagster:
            asset_key: ["gold", "metricVideos"]
      - name: informationVideos
        meta:
          dagster:
            asset_key: ["gold", "informationVideos"]